{{- if index .Values "cert-manager" "install" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "name" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end }}
