image: registry.gitlab.com/gitlab-org/gitlab-build-images:gitlab-operator-build-base

stages:
  - prepare
  - test
  - build
  - release

.cache:
  variables:
    GOPATH: "${CI_PROJECT_DIR}/.go"
  before_script:
    - mkdir -p .go charts
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .go/pkg/mod/
      - charts/

.docker_build_job: &docker_build_job
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  script:
    - docker build -t "${DOCKER_IMAGE}" -f "${DOCKER_FILE:-Dockerfile}" .
    - docker push "${DOCKER_IMAGE}"
  extends: .cache

lint_code:
  stage: prepare
  script:
    - /go/bin/golint -set_exit_status $(go list ./... | grep -v /vendor/)
  extends: .cache

pull_charts:
  stage: prepare
  script:
    - scripts/retrieve_gitlab_charts.sh
  extends: .cache

unit_tests:
  stage: test
  script:
    - export HELM_CHARTS="${PWD}/charts"
    - mkdir coverage
    - /go/bin/ginkgo -cover -outputdir=coverage ./...
  extends: .cache

build_all:
  stage: build
  script:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo ./...
  extends: .cache

build_latest_image:
  <<: *docker_build_job
  stage: release
  variables:
    DOCKER_IMAGE: "${CI_REGISTRY_IMAGE}:latest"
  only:
    - master

build_branch_image:
  <<: *docker_build_job
  stage: release
  variables:
    DOCKER_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
  except:
    - master

build_bundle_image:
  <<: *docker_build_job
  stage: release
  variables:
    DOCKER_IMAGE: "${CI_REGISTRY_IMAGE}/bundle"
    DOCKER_FILE: Dockerfile.bundle
  only:
    - master
