resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: registry.gitlab.com/gitlab-org/gl-openshift/gitlab-operator
  newName: registry.gitlab.com/gitlab-org/gl-openshift/gitlab-operator
  newTag: latest
