{{- if .Values.app.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "app.serviceAccount.name" . }}-rolebinding-nonroot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "app.serviceAccount.name" . }}-role-nonroot
subjects:
- kind: ServiceAccount
  name: {{ include "app.serviceAccount.name" . }}-nonroot
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "app.serviceAccount.name" . }}-rolebinding-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "app.serviceAccount.name" . }}-role-anyuid
subjects:
- kind: ServiceAccount
  name: {{ include "app.serviceAccount.name" . }}-anyuid
  namespace: {{ .Release.Namespace }}
{{- end }}
