#!/bin/bash
echo "Initial HOSTSUFFIX ${HOSTSUFFIX}"
echo "Initial TESTS_NAMESPACE ${TESTS_NAMESPACE}"
export OLD_HOSTSUFFIX=${HOSTSUFFIX}
export OLD_TESTS_NAMESPACE=${TESTS_NAMESPACE}
export TESTS_NAMESPACE=${TESTS_NAMESPACE:0:63}
export HOSTSUFFIX=${HOSTSUFFIX:0:63}
echo "Trimmed HOSTSUFFIX ${HOSTSUFFIX}"
echo "Trimmed TESTS_NAMESPACE ${TESTS_NAMESPACE}"