# permissions for end users to view gitlabs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-viewer-role
rules:
- apiGroups:
  - apps.gitlab.com
  resources:
  - gitlabs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.gitlab.com
  resources:
  - gitlabs/status
  verbs:
  - get
