# permissions for end users to edit glbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: glbackup-editor-role
rules:
- apiGroups:
  - apps.gitlab.com
  resources:
  - glbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.gitlab.com
  resources:
  - glbackups/status
  verbs:
  - get
