# permissions for end users to view glbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: glbackup-viewer-role
rules:
- apiGroups:
  - apps.gitlab.com
  resources:
  - glbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.gitlab.com
  resources:
  - glbackups/status
  verbs:
  - get
