namePrefix:
- path: metadata/name
  kind: ClusterRoleBinding

# ensures that SCC in Role matches SCC name with prefix.
nameReference:
  - kind: SecurityContextConstraints
    fieldSpecs:
      - path: rules/resourceNames
        kind: Role
      - path: rules/resourceNames
        kind: ClusterRole
