apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: runners.gitlab.com
spec:
  group: gitlab.com
  names:
    kind: Runner
    listKind: RunnerList
    plural: runners
    singular: runner
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Runner is the Schema for the runners API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RunnerSpec defines the desired state of Runner
          properties:
            gitlab:
              description: GitlabResource represents a Gitlab custom resource. Should
                only be used to reference Gitlab instance created by the operator
              properties:
                name:
                  description: Name of gitlab resource in kubernetes / openshift
                  type: string
              type: object
            instanceURL:
              description: Gitlab or Continuous Integration URL
              type: string
            token:
              description: Gitlab Runner registration token
              type: string
          type: object
        status:
          description: RunnerStatus defines the observed state of Runner
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
