apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gitlabs.gitlab.com
spec:
  group: gitlab.com
  names:
    kind: Gitlab
    listKind: GitlabList
    plural: gitlabs
    singular: gitlab
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Gitlab is the Schema for the gitlabs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GitlabSpec defines the desired state of Gitlab
          properties:
            certificate:
              type: string
            database:
              description: DatabaseSpec defines database options
              properties:
                replicas:
                  format: int32
                  type: integer
              type: object
            email:
              description: 'SMTPConfiguration defines options for Gitlab registry
                More on configuration options available below: https://docs.gitlab.com/omnibus/settings/smtp.html'
              properties:
                authentication:
                  description: 'Authentication represents authentication mechanism
                    Options include: login, plain, false'
                  type: string
                displayName:
                  description: DisplayName represents the name of the email
                  type: string
                domain:
                  description: Domain represents the email domain
                  type: string
                enable:
                  type: boolean
                enableSSL:
                  description: EnableSSL enables/disables SSL
                  type: boolean
                enableStartTLS:
                  description: EnableStartTLS
                  type: boolean
                forceSSL:
                  description: ForceSSL determines if gitlab should force use of SSL
                    certificates
                  type: boolean
                from:
                  description: EmailFrom represents the from address of outgoing email
                  type: string
                host:
                  description: Host is the SMTP host
                  type: string
                opensslVerifyMode:
                  description: 'OpensslVerifyMode can be: ''none'', ''peer'', ''client_once'',
                    ''fail_if_no_peer_cert'''
                  type: string
                password:
                  description: Password represents the password for SMTP user
                  type: string
                port:
                  description: Port represents SMTP port
                  type: integer
                replyTo:
                  description: ReplyTO specifies a reply to email address
                  type: string
                tls:
                  description: TLS enables/disables use of TLS certificates
                  type: boolean
                username:
                  description: Username represents the SMTP username for sending email
                  type: string
              type: object
            enterprise:
              type: boolean
            externalURL:
              type: string
            redis:
              description: RedisSpec defines Redis options
              properties:
                replicas:
                  format: int32
                  type: integer
              type: object
            registry:
              description: RegistrySpec defines options for Gitlab registry
              properties:
                enable:
                  type: boolean
                externalURL:
                  type: string
              type: object
            replicas:
              format: int32
              type: integer
            volumes:
              description: ComponentVolumeSpec defines volumes for the different Gitlab
                peieces
              properties:
                config:
                  description: Gitlab configuration volume
                  properties:
                    capacity:
                      description: Sets the size of the volume
                      type: string
                    persist:
                      description: Sets whether the data or volume should persist
                        Should create emptyDir if set to false instead of PVC
                      type: boolean
                  type: object
                data:
                  description: Gitlab rails data volume
                  properties:
                    capacity:
                      description: Sets the size of the volume
                      type: string
                    persist:
                      description: Sets whether the data or volume should persist
                        Should create emptyDir if set to false instead of PVC
                      type: boolean
                  type: object
                database:
                  description: Postgres database volume for PGDATA
                  properties:
                    capacity:
                      description: Sets the size of the volume
                      type: string
                    persist:
                      description: Sets whether the data or volume should persist
                        Should create emptyDir if set to false instead of PVC
                      type: boolean
                  type: object
                redis:
                  description: Redis key value store volume
                  properties:
                    capacity:
                      description: Sets the size of the volume
                      type: string
                    persist:
                      description: Sets whether the data or volume should persist
                        Should create emptyDir if set to false instead of PVC
                      type: boolean
                  type: object
                registry:
                  description: Gitlab registry volume
                  properties:
                    capacity:
                      description: Sets the size of the volume
                      type: string
                    persist:
                      description: Sets whether the data or volume should persist
                        Should create emptyDir if set to false instead of PVC
                      type: boolean
                  type: object
              type: object
          required:
          - replicas
          type: object
        status:
          description: GitlabStatus defines the observed state of Gitlab
          properties:
            phase:
              description: Phase represents status of the Gitlab resource
              type: string
            services:
              description: ServicesHealth represents the status  of a Gitlab dependent
                service
              properties:
                database:
                  type: string
                redis:
                  type: string
              type: object
            stage:
              type: string
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
