apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: gitlab-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: gitlab-runner
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  - events
  - services
  - services/status
  - services/proxy
  - services/finalizers
  - resourcequotas
  - pods/attach
  - pods/exec
  - pods/log
  - persistentvolumeclaims
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - patch
  - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-runner
subjects:
- kind: ServiceAccount
  name: gitlab-runner
roleRef:
  kind: Role
  name: gitlab-runner
  apiGroup: rbac.authorization.k8s.io
