kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-rolebinding
subjects:
- kind: ServiceAccount
  name: app
  namespace: system
roleRef:
  kind: ClusterRole
  name: app-role
  apiGroup: rbac.authorization.k8s.io
