# The following patch sets spec.preserveUnknownFields to false in the CRD
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gitlabs.apps.gitlab.com
spec:
  preserveUnknownFields: false