#due to https://github.com/kubernetes-sigs/kustomize/issues/4164 
#namePrefix == nameSuffix
namePrefix:
  - kind: ClusterRole
    path: metadata/name
  - kind: ClusterRoleBinding
    path: metadata/name

# ensures that SCC in Role matches SCC name with prefix.
nameReference:
  - kind: CustomResourceDefinition
    fieldSpecs:
      - path: metadata/annotations/cert-manager.io\/inject-ca-from
        kind: Certificate
  - kind: SecurityContextConstraints
    fieldSpecs:
      - path: rules/resourceNames
        kind: Role
      - path: rules/resourceNames
        kind: ClusterRole

namespace:
- kind: RoleBinding
  group: rbac.authorization.k8s.io
  version: v1
  path: subjects/namespace
  create: false
- kind: CustomResourceDefinition
  path: spec/conversion/webhookClientConfig/service/namespace

varReference:
- kind: Certificate
  group: cert-manager.io
  path: spec/commonName
- kind: Certificate
  group: cert-manager.io
  path: spec/dnsNames
