installCRDs: true
image:
  repository: registry.connect.redhat.com/jetstack/cert-manager-controller
  tag: v1.1.0-ubi
webhook:
  image:
    repository: registry.connect.redhat.com/jetstack/cert-manager-webhook
    tag: v1.1.0-ubi
cainjector:
  image:
    repository: registry.connect.redhat.com/jetstack/cert-manager-cainjector
    tag: v1.1.0-ubi
extraArgs:
  - --dns01-recursive-nameservers-only=true
  - --dns01-recursive-nameservers=8.8.8.8:53,8.8.4.4:53
  - --acme-http01-solver-image=registry.connect.redhat.com/jetstack/cert-manager-acmesolver:v1.1.0-ubi
