apiVersion: k8s.nginx.org/v1alpha1
kind: NginxIngressController
metadata:
  name: nginx-ingress-controller
  namespace: default
spec:
  ingressClass: nginx
  serviceType: LoadBalancer
  replicas: 1
  nginxPlus: false
  type: deployment
  image:
    pullPolicy: Always
    repository: docker.io/nginx/nginx-ingress
    tag: 1.10.1-ubi
