# Patch Certificate based on generated service name and present namespace
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-serving-cert  
  namespace: gitlab-system
spec:
  dnsNames:
  - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc
  - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.cluster.local
